# Generated by Django 4.2.5 on 2023-12-27 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=50)),
                ('post_text', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='facebook_access_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='twitter_access_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='SocialMediaIntegration',
        ),
        migrations.AddField(
            model_name='socialmediapost',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_media_dashboard.userprofile'),
        ),
    ]
