# Generated by Django 4.2.5 on 2023-12-28 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_dashboard', '0003_socialmediapost_comments_socialmediapost_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='twitter_access_token_secret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
